name: Dev Build & Audit

on:
  push:
    branches: [ "dev" ]

jobs:
  build-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies and audit tool
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pip-audit
      - name: Run tests
        run: pytest
      - name: Run pip-audit
        run: pip-audit -r requirements.txt
      - name: Build Docker image
        run: docker build -t app:dev-${{ github.sha }} .