name: Release Build

on:
  push:
    branches: [ "main" ]

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies and security tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest bandit
      - name: Run tests
        run: pytest
      - name: Security scan with bandit
        run: bandit -r app/
      - name: Build Docker image
        run: docker build -t app:release-${{ github.sha }} .
      - name: Save Docker image to file
        run: |
          docker save app:release-${{ github.sha }} -o docker-image.tar
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-image
          path: docker-image.tar