name: Main Release & GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit mkdocs
          pip install pytest

      - name: Run unit tests
        run: pytest -q

      - name: Lint with flake8
        run: flake8 app test

      - name: Run bandit security checks
        run: bandit -r app -ll
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t complex-demo:latest .

      - name: Inject commit SHA into docs
        run: |
          sed -i "s/{{COMMIT_SHA}}/${{ github.sha }}/g" docs/index.md

      - name: Build static site
        run: mkdocs build --strict --clean -d site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4